export const UNIVERSE_SECTOR_MAP: Record<string, string> = {
  AAPL: "Technology",
  MSFT: "Technology",
  NVDA: "Technology",
  AVGO: "Technology",
  ORCL: "Technology",
  AMD: "Technology",
  QCOM: "Technology",
  TXN: "Technology",
  AMAT: "Technology",
  ASML: "Technology",
  GOOGL: "Communication",
  META: "Communication",
  NFLX: "Communication",
  DIS: "Communication",
  CMCSA: "Communication",
  VZ: "Communication",
  T: "Communication",
  AMZN: "Consumer Discretionary",
  TSLA: "Consumer Discretionary",
  HD: "Consumer Discretionary",
  MCD: "Consumer Discretionary",
  NKE: "Consumer Discretionary",
  SBUX: "Consumer Discretionary",
  TGT: "Consumer Discretionary",
  BKNG: "Consumer Discretionary",
  ABNB: "Consumer Discretionary",
  UBER: "Consumer Discretionary",
  WMT: "Consumer Staples",
  COST: "Consumer Staples",
  PG: "Consumer Staples",
  KO: "Consumer Staples",
  PEP: "Consumer Staples",
  PM: "Consumer Staples",
  MO: "Consumer Staples",
  JPM: "Financials",
  BAC: "Financials",
  WFC: "Financials",
  GS: "Financials",
  MS: "Financials",
  BLK: "Financials",
  V: "Financials",
  MA: "Financials",
  AXP: "Financials",
  C: "Financials",
  LLY: "Healthcare",
  JNJ: "Healthcare",
  ABBV: "Healthcare",
  MRK: "Healthcare",
  PFE: "Healthcare",
  TMO: "Healthcare",
  ABT: "Healthcare",
  DHR: "Healthcare",
  BMY: "Healthcare",
  AMGN: "Healthcare",
  CAT: "Industrials",
  RTX: "Industrials",
  HON: "Industrials",
  UPS: "Industrials",
  BA: "Industrials",
  GE: "Industrials",
  MMM: "Industrials",
  LMT: "Industrials",
  DE: "Industrials",
  XOM: "Energy",
  CVX: "Energy",
  COP: "Energy",
  SLB: "Energy",
  EOG: "Energy",
  LIN: "Materials",
  APD: "Materials",
  ECL: "Materials",
  NEM: "Materials",
  FCX: "Materials",
  AMT: "Real Estate",
  PLD: "Real Estate",
  EQIX: "Real Estate",
  CCI: "Real Estate",
  NEE: "Utilities",
  DUK: "Utilities",
  SO: "Utilities",
  D: "Utilities",
  TSM: "Technology",
  MU: "Technology",
  INTC: "Technology",
  MRVL: "Technology",
  KLAC: "Technology",
  LRCX: "Technology",
  CRM: "Technology",
  NOW: "Technology",
  SNOW: "Technology",
  PLTR: "Technology",
  COIN: "Financials",
  MSTR: "Technology",
  SQ: "Financials",
  PYPL: "Financials",
  "BRK.B": "Financials",
  UNH: "Healthcare",
  CVS: "Healthcare",
  MDLZ: "Consumer Staples",
  GILD: "Healthcare",
  ISRG: "Healthcare",
  ZTS: "Healthcare",
  REGN: "Healthcare",
};

export function getUniverseSector(ticker: string) {
  return UNIVERSE_SECTOR_MAP[ticker.trim().toUpperCase()] ?? "Unknown";
}
