export const alqisDesignTokens = {
  color: {
    background: "var(--background)",
    surface: "var(--surface)",
    surfaceElevated: "var(--surface-elevated)",
    surfaceAlt: "var(--surface-alt)",
    border: "var(--border)",
    borderStrong: "var(--border-strong)",
    textPrimary: "var(--text-primary)",
    textSecondary: "var(--text-secondary)",
    textMuted: "var(--text-muted)",
    textDisabled: "var(--text-disabled)",
    accentPrimary: "var(--accent-primary)",
    accentSecondary: "var(--accent-secondary)",
    accentAI: "var(--accent-ai)",
    positive: "var(--positive)",
    positiveBg: "var(--positive-bg)",
    negative: "var(--negative)",
    negativeBg: "var(--negative-bg)",
    warning: "var(--warning)",
    warningBg: "var(--warning-bg)",
    info: "var(--info)",
    infoBg: "var(--info-bg)",
    bg: "var(--bg)",
    bgMuted: "var(--bg-muted)",
    surfaceStrong: "var(--surface-strong)",
    ink: "var(--ink)",
    inkMuted: "var(--ink-muted)",
    inkSubtle: "var(--ink-subtle)",
    accent: "var(--accent)",
    accentMuted: "var(--accent-muted)",
    gain: "var(--gain)",
    gainBg: "var(--gain-bg)",
    loss: "var(--loss)",
    lossBg: "var(--loss-bg)",
    warn: "var(--warn)",
    warnBg: "var(--warn-bg)",
    infoMuted: "var(--info-muted)",
    danger: "var(--danger)",
  },
  type: {
    display: "var(--type-display)",
    pageTitle: "var(--type-page-title)",
    sectionTitle: "var(--type-section-title)",
    cardTitle: "var(--type-card-title)",
    bodyLg: "var(--type-body-lg)",
    body: "var(--type-body)",
    bodySm: "var(--type-body-sm)",
    label: "var(--type-label)",
  },
  spacing: {
    "2xs": "var(--space-2xs)",
    xs: "var(--space-xs)",
    sm: "var(--space-sm)",
    md: "var(--space-md)",
    lg: "var(--space-lg)",
    xl: "var(--space-xl)",
    "2xl": "var(--space-2xl)",
    "3xl": "var(--space-3xl)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
  },
  shadow: {
    low: "var(--shadow-1)",
    medium: "var(--shadow-2)",
    high: "var(--shadow-3)",
  },
  layout: {
    containerMax: "var(--container-max)",
    readingMax: "var(--container-reading)",
    mobilePadding: "var(--page-padding-mobile)",
    desktopPadding: "var(--page-padding-desktop)",
  },
} as const;

export const alqisDesignGuidance = {
  accentUsage:
    "Use accent color to point at action, selected states, and one dominant chart highlight. Avoid stacking accent on multiple neighboring surfaces.",
  elevation:
    "Reserve the strongest shadow for focal cards or chart containers. Default panels should rely on border and subtle blur before shadow.",
  denseData:
    "Compress with alignment, consistent labels, and grouped rows rather than smaller type. Keep 14px-15px body text as the floor for primary financial reading.",
  layout:
    "Let whitespace separate major decisions. Use tighter gaps only inside dense financial modules, never between major sections.",
} as const;
